---
BaseUrl: "http://www.ryanclarke.net/"
LanguageCode: "en-us"
Title: "Ryan Clarke"
MetaDataFormat: "yaml"
Theme: "lagom"
PublishDir: "../"
Copyright: "© 2014 Ryan Clarke"
Author:
  name: "Ryan Clarke"
Params:
  Description: "The blog of Ryan Clarke"
  Tagline: "Varied submissions of an adventurer"
  AuthorName: "Ryan Clarke"
  AuthorNameUrl: "/about"
  Github: "ryanclarke"
  Twitter: "RyanSClarke"
Menu:
  Main:
  - Url: "/about"
    Name: "About"
...
